baseURL = "https://theweeklychallenge.org/"
locale = "en-us"
title = "The Weekly Challenge"
theme = "twc-theme"
publishDir = "docs"
rssLimit = 10

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

[taxonomies]
  tag = "tags"

[outputFormats]

  [outputFormats.JSON]
    mediaType = "application/json"
    baseName  = "index"
    isHTML    = false
    notAlternative = true
  [outputFormats.HTML]
    notAlternative = true

  [outputFormats.CurrentJSON]
    mediaType = "application/json"
    baseName  = "current"
    isHTML    = false
    notAlternative = true

  [outputFormats.BlogsJSON]
    mediaType = "application/json"
    baseName  = "blogs"
    isHTML    = false
    notAlternative = true

  [outputFormats.ChampionsJSON]
    mediaType = "application/json"
    baseName  = "champions"
    isHTML    = false
    notAlternative = true

  [outputFormats.PerlReviewsJSON]
    mediaType = "application/json"
    baseName  = "perl-reviews"
    isHTML    = false
    notAlternative = true

  [outputFormats.RakuReviewsJSON]
    mediaType = "application/json"
    baseName  = "raku-reviews"
    isHTML    = false
    notAlternative = true

  [outputFormats.PostJSON]
    mediaType = "application/json"
    baseName  = "post"
    isHTML    = false
    notAlternative = true

  [outputFormats.GuestsListJSON]
    mediaType = "application/json"
    baseName  = "guests-list"
    isHTML    = false
    notAlternative = true

  [outputFormats.RegularsJSON]
    mediaType = "application/json"
    baseName  = "regulars"
    isHTML    = false
    notAlternative = true

  [outputFormats.GuestContribsJSON]
    mediaType = "application/json"
    baseName  = "guest-contributions"
    isHTML    = false
    notAlternative = true

  [outputFormats.AboutJSON]
    mediaType = "application/json"
    baseName  = "about"
    isHTML    = false
    notAlternative = true


[outputs]
  home = ["HTML", "RSS", "JSON", "CurrentJSON", "BlogsJSON", "ChampionsJSON", "PerlReviewsJSON", "RakuReviewsJSON", "GuestsListJSON", "RegularsJSON", "GuestContribsJSON", "AboutJSON"]
  page = ["HTML", "PostJSON"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Chart"
        url     = "/chart"
        weight  = 3
    [[menu.nav]]
        name    = "Champions"
        url     = "/champions"
        weight  = 4
    [[menu.nav]]
        name    = "Team"
        url     = "/team"
        weight  = 5
    [[menu.nav]]
        name    = "Challenges"
        url     = "/challenges"
        weight  = 6
    [[menu.nav]]
        name    = "Perl/Review"
        url     = "/p5-reviews"
        weight  = 7
    [[menu.nav]]
        name    = "Raku/Review"
        url     = "/p6-reviews"
        weight  = 8
    [[menu.nav]]
        name    = "Recaps"
        url     = "/recaps"
        weight  = 9
    [[menu.nav]]
        name    = "Blogs"
        url     = "/blogs"
        weight  = 10
    [[menu.nav]]
        name    = "FAQ"
        url     = "/faq"
        weight  = 11
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 12

# Site Params
[params]
    home = "Home"
    logo = "images/logo.svg"
    dateFormat = "25 March 2019"
    # Meta data
    author        = "Mohammad Sajid Anwar"
    description   = "You don't have to be an expert"
    ogImage       = "images/og-image.jpg"
    twitterHandle = "@PerlWChallenge"
    currentWeek   = 367

    [params.sponsors]
    paypal = "https://paypal.me/perlweeklychallenge"

    [[params.sponsors.current]]
      name        = "Marc Perry, PhD"
      url         = "https://www.linkedin.com/in/marcperry"
      description = "Senior Bioinformatics Data Engineer"
      since       = "Jan 2026"

    [[params.sponsors.past]]
      name        = "Pete Sergeant"
      url         = "https://www.linkedin.com/in/petersergeant"
      description = "Owner of Perl Careers, global recruitment agency."
      since       = "Sponsored Jun 2021 – Dec 2023"

    [[params.sponsors.past]]
      name        = "Lance Wicks"
      url         = "https://www.linkedin.com/in/lancew"
      description = "Software Development Manager for a large UK recruitment website."
      since       = "Sponsored Jan 2024 – Dec 2025"

    [[params.sponsors.supporters]]
      name  = "Matthias Muth"
      since = "One-off · Mar 2026"

    [[params.sponsors.supporters]]
      name  = "David Ferrone"
      since = "One-off · Jan 2026"

    [[params.sponsors.supporters]]
      name  = "Ulrich Rieke"
      since = "One-off · Jan 2025"

    [[params.sponsors.supporters]]
      name  = "Peter Meszaros"
      since = "One-off · Dec 2025"

    # Google Analitycs
    googleAnalitycsID = "UA-136524905-1"

    [params.weekYears]
        "2019" = [1, 32]
        "2020" = [33, 84]
        "2021" = [85, 136]
        "2022" = [137, 189]
        "2023" = [190, 241]
        "2024" = [242, 293]
        "2025" = [294, 345]
        "2026" = [346, 400]

    # Banner Section
    [params.banner]
        brandImage = "images/about/about.jpg"
        description = "You don't have to be an expert"
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "The Weekly Challenge"
        btn     = true
        taskLabel1 = "Max Odd Binary"
        taskDesc1  = "You are given a binary string that has at least one '1'. Write a script to rearrange the bits in such a way that the resulting binary number is the maximum odd binary number and return the resulting binary string. The resulting string can have leading zeros."
        taskLabel2 = "Conflict Events"
        taskDesc2  = "You are given two events start and end time. Write a script to find out if there is a conflict between the two events. A conflict happens when two events have some non-empty intersection."
        guestContributionsURL = "/guest-contributions"
        latestChampionURL = "/blog/meet-the-champion-2024-01"
        perlReviewURL = "/blog/review-challenge-180"
        rakuReviewURL = "/blog/p6-review-challenge-273"
        youTubeChannelURL = "https://www.youtube.com/c/mohammadsajidanwar"
        howToContributeURL = "/blog/how-to-contribute"
        btnText = "🔍 Take the Challenge"
        btnURL  = "/blog/perl-weekly-challenge-367"
        [[params.banner.flipText]]
            title   = "Champion"
        [[params.banner.flipText]]
            title   = "Contributor"
        [[params.banner.flipText]]
            title   = "Mentor"

    # Enable HTML in markup, needed for image control
    [markup.goldmark.renderer]
        unsafe  = true

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        email   = "mohammad.anwar@yahoo.com"
        image   = "images/team/mohammad_anwar.jpg"
        github   = "https://github.com/manwar"
        twitter  = "https://twitter.com/cpan_author"
        linkedin = "http://www.linkedin.com/in/mohammadanwar"
        mastodon = "https://fosstodon.org/@manwar"
        website = "https://manwar.org"
        subtitle1 = "JAMSHEDPUR, INDIA (1993 - 1997)"
        content1 = "Let me share my journey of how I got into computing. It all started in 1993, just after I joined a three-year B.Sc. (Math Honours) degree course. During that first year, I realised that a degree alone wouldn't be enough to secure the job I desperately needed to support my family. A friend asked if I was interested in joining a computer training course. Without a second thought, I decided to join him and went to a local branch of APTECH, a well-known computer training institute in India. When we arrived and inquired about their offerings, we were told we had to pass an aptitude test before enrolling. I wasn't prepared, but I decided to give it a try anyway. We both secured over 90% on the test. My friend, who was fully prepared, began discussing the options and eventually chose a one-year \"Diploma in Information and Systems Management\" (DISM). At the time, the fee was INR 13,000. I didn't have the money to join, but when I told my mother, she did what any devoted mother would do: she sold her wedding jewelry to pay my fees. It was vital for me to start earning as soon as possible, and I hoped this course would lead to a decent job. I started the course six months later. On my very first day, I was surprised to find that the same friend was now my instructor! He was such a bright student that APTECH had offered him a job while he was still completing his own studies. We were taught FoxPro and COBOL as part of the curriculum. By the end of the course, I wasn't satisfied with the depth of my knowledge, so I decided to learn other programming languages. The trouble was that I didn't own a PC or laptop, nor did I have enough money for books. I joined a local library called the \"Muslim Library\" because it was free. It was far from where I lived, requiring two bus journeys, and sometimes I didn't even have enough money for the fare. My older sister, who earned money through home tutoring, always helped me out. I learned Pascal simply by reading. When I moved on to C, I discovered another friend was running a computer training institute. I asked if I could use his PCs whenever they were available; in return, I offered to teach his students. He kindly accepted. While exploring C, I saw an advertisement for a multinational training center called INFOTECH opening in Jamshedpur. I applied for a faculty position but was offered a role as a \"Lab Assistant\" for INR 2,000 per month. To me, that was a lot of money; it allowed me to support my family, especially my younger brother who was still in college. Being a Lab Assistant had an added advantage: I had unlimited access to the PCs. I learned Oracle during my time there and was promoted to the Faculty team a year later."
        subtitle2 = "MUMBAI, INDIA (1997 - 2000)"
        content2 = "In 1997, I decided to move to a larger city in search of better opportunities. One of my colleagues at INFOTECH was headed to Mumbai to try his luck, so I decided to join him, as I didn't know anyone else there. The first three months were incredibly tough. My colleague quickly received a great offer from a major technology firm, while I continued to struggle. Eventually, out of necessity, I joined APTECH as a faculty member. It was a matter of survival; I didn't particularly like the job because I was looking for a programming role, but I had no other choice. After a year or so, the branch manager at APTECH asked if I was interested in a small, part-time project using FoxPro. I accepted without hesitation. This became my first professional programming role, where we built a Windows desktop application for a local rubber factory. During this time, a friend of a friend from Jamshedpur asked if I was interested in a Perl programming role. It was at a startup called INFOFIN, and they were looking for someone keen to learn the language. I interviewed and got the job. It was both more satisfying and better paid—INR 7,000 per month compared to the INR 5,000 I earned at APTECH. For the first time, I learned web programming using the \"good old\" CGI.pm and DBI.pm. There were no templates back then; everything was handled directly within the CGI scripts. A year and a half later, I saw an advertisement from a multinational company, ORIENT, looking for Perl developers. By then, I knew enough Perl to feel confident, so I decided to give it a try. By the grace of Allah, I got the job. I could hardly believe it when they told me my salary would be INR 15,000 per month. I was a little worried, though, that such a high salary would come with equally high expectations. My first day at the office was very interesting. I saw over 20 programmers from various backgrounds sitting around and doing nothing all day. We even received free lunch. It didn't take me long to figure out the business model: it was a form of \"body-shopping\". They would hire programmers and then send them abroad for contracting, mainly to the UK and the USA. When I was asked for my choice of location, I randomly picked the UK."
        subtitle3 = "LONDON, ENGLAND (2000 - till date)"
        content3 = "I still remember arriving at Heathrow Airport on a Sunday evening, April 2nd, 2000. My manager from the London office picked me up and took me to a Gujarati family's home in Wembley, where ten other programmers were already staying. I had come to the UK on a two-year work permit with a take-home pay package of £1,600 after tax. My first few months were quite difficult. Communication, particularly in English, had never been my forte, and I faced numerous challenges wherever I went for contracting roles. Eventually, I secured a two-week contract in the City. On the very first day, I impressed my line manager by solving an issue that had baffled them for months. By the end of that day, she offered me a six-month extension; I was thrilled, especially as she was incredibly understanding. After that, I took another two-month contract in Dublin with Vodafone. It was a wonderful experience; the people there were very friendly. I returned to London in December 2000 and began a contract with a company called Torrington Interactive, based in the City. I worked on the \"Tuskerdirect\" project, but within a few months, the company went into liquidation. Fortunately, the IT manager of Tuskerdirect approached me and offered me a permanent position instead of a contract. Since I had never truly enjoyed the uncertainty of contracting, I accepted immediately. My pay package increased to £2,600 after tax. I stayed there for five years, the longest I had ever been at one company at that time. Following that, I joined Spinvox, where I had the pleasure of working with Neil Bowers on an SMS-sending module. Two years later, during a round of redundancies, I left that position and returned to the City. I have now been working at Oleeo for nearly five years."

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT DO YOU THINK ?"
        content = "If you have any suggestions or ideas then please do share with us."
        btnText = "Contact with me"
        btnURL  = "mailto:mohammad.anwar@yahoo.com"

